### ISSUE TITLE
兄弟 你这个类坑的我好久

### ISSUE THREAD

**Issue by MkMarko** [hao-li/laravel-amount#9]
你为啥在.gitignore去忽略/vendor/文件呢? 导致我上传git的时候一直没有这个类的内容，每次下载代码我都需要重新去composer required你的类

**Comment by hao-li** [comment]
没太明白你说的问题具体是啥

一般情况下 部署时执行 `composer install` 会自动生成 vendor 所以我加到了 .gitignore 里面

**Comment by MkMarko** [comment]
嗯 意思就是 我本身是用了git同步代码的，我在公司有一套 在家里有一套，然后我git同步的时候会把vendor的文件同步上去，然后在家里拉取下来就可以用了，但是因为你的忽略文件，导致我的需要扩展都无法上传到git，所以我每次都需要 composer install安装一遍



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "hao-li"<notifications@github.com&gt;; 
发送时间: 2020年7月7日(星期二) 下午2:36
收件人: "hao-li/laravel-amount"<laravel-amount@noreply.github.com&gt;; 
抄送: "M.K"<275535133@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [hao-li/laravel-amount] 兄弟 你这个类坑的我好久 (#9)





 
没太明白你说的问题具体是啥
 
一般情况下 部署时执行 composer install 会自动生成 vendor 所以我加到了 .gitignore 里面

**Comment by hao-li** [comment]
嗯 你的新习惯挺好的
一般的项目都不会提交 vendor
以后同步后也记得继续 `composer install` ；）

**Comment by MkMarko** [comment]
哈哈 我建议是你的忽略文件不应该忽略/vendor/因为不同人有不同的需求 我看其他人开发的最多也是忽略这个插件的文件夹

**Comment by hao-li** [comment]
灵活的代价是使用的麻烦 两者基本反比
所以还是随大流来吧 都比较省事
